# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql:8
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: M7vDRWBJW1EAGzih
    ports:
        - 3306:3306
    volumes:
      - ".\\project3bdscript.sql:/root/project3bdscript.sql"